// RC(MODULE, RC_NAME)

RC(LEXER, EOF)
RC(LEXER, GET_NEXT_TOKEN_FAILED)

RC(PROMPT, EOF)

RC(RUNNER, INVALID_ID_LENGTH)
RC(RUNNER, COMMAND_ALREADY_HAS_A_SYMBOL_NAME)
RC(RUNNER, FUNCTION_SETUP_FAILED)
RC(RUNNER, FAILED_TO_FIND_FUNCTION_SYMBOL)
RC(RUNNER, FAILED_TO_OPEN_SHARED_OBJECT)