// RC(MODULE, RC_NAME)

RC(ENTRYPOINT, FAILED_TO_REGISTER_SIGTERM_HANDLER)
RC(ENTRYPOINT, FAILED_TO_CREATE_PIPE)

RC(LEXER, EOF)
RC(LEXER, GET_NEXT_TOKEN_FAILED)

RC(PROMPT, EOF)

RC(RUNNER, FAILED_TO_OPEN_SHARED_OBJECT)

RC(COMMAND, NULL_PARSER)
RC(COMMAND, SYMBOL_ALREADY_EXISTS)
RC(COMMAND, SYMBOL_INVALID_LENGTH)
RC(COMMAND, FUNCTION_SETUP_FAILED)
